<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="AASHYD-4B6B2X2" name="com.vrt.testcases.LoginTest" tests="17" failures="1" timestamp="22 Aug 2019 13:09:14 GMT" time="371.490" errors="0">
  <testcase name="LOGIN_008" time="7.653" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_002" time="6.339" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_003" time="6.798" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_007" time="8.718" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_009" time="18.206" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_016" time="24.475" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_020" time="82.457" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_013" time="10.803" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_019" time="49.421" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_017_018" time="46.738" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_004" time="8.189" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_010" time="7.646" classname="com.vrt.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	FAIL: The 1st User is allowed to Change its PW on 1st time Login expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
FAIL: The 1st User is allowed to Change its PW on 1st time Login expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.vrt.testcases.LoginTest.LOGIN_010(LoginTest.java:245)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LOGIN_010 -->
  <testcase name="LOGIN_012" time="16.111" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_005" time="27.353" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_014" time="21.145" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_001" time="12.812" classname="com.vrt.testcases.LoginTest"/>
  <testcase name="LOGIN_015" time="16.626" classname="com.vrt.testcases.LoginTest"/>
</testsuite> <!-- com.vrt.testcases.LoginTest -->
